app/models.py
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

db = SQLAlchemy()

shop_cart = db.Table(
    'shop_cart',
    db.Column('user', db.Integer, db.ForeignKey('user.id'), nullable=False),
    db.Column('product', db.Integer, db.ForeignKey('product.id'), nullable=False))

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), nullable=False, unique=True)
    email = db.Column(db.String, nullable=False, unique=True)
    password = db.Column(db.String, nullable=False)
    
    def __init__(self, username, email, password):
        self.username = username
        self.email = email
        self.password = password

    def save_user(self):
        db.session.add(self)
        db.session.commit()


    def addCart(self, product):
        self.add_to_cart.append(product)
=======
class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    price = db.Column(db.Numeric, nullable=False)
    description = db.Column(db.String, nullable=False)

    def __init__(self, name, price, description):
        self.name = name
        self.price = price
        self.description = description


    def save_product(self):
        db.session.add(self)
        db.session.commit()

    def removeCart(self, product):
        self.add_to_cart.remove(product)
        db.session.commit()


class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    price = db.Column(db.Numeric(12,2), nullable=False)
    description = db.Column(db.String, nullable=False)
    image = db.Column(db.String, nullable=True)

    add_to_cart= db.relationship('User', 
        secondary = 'shop_cart',
        backref = 'add_to_cart',
        lazy = 'dynamic'
            )                      

    def __init__(self, name, price, description, image):
        self.name = name
        self.price = price
        self.description = description
        self.image = image

    def save_product(self):
        db.session.add(self)
        db.session.commit()

app/__init__.py
from flask import Flask

from config import Config

from .auth.routes import auth

from .cart.routes import cart 

from .models import db, User, Product

from flask_migrate import Migrate

app = Flask(__name__)

app.config.from_object(Config)

db.init_app(app)
migrate = Migrate(app, db)

app.register_blueprint(auth)

app.register_blueprint(cart)



from . import routes
from . import models

app/cart/routes.py
from flask import render_template, Blueprint, request, redirect, url_for
from ..models import User, Product
from flask_login import current_user

cart = Blueprint('cart', __name__, template_folder='cart_templates')


@cart.route('/cart')
def show_cart():
    user = current_user
    cart_items = user.add_to_cart.all()
    return render_template('cart.html', cart_items=cart_items)


@cart.route('/add_to_cart/<int:product_id>')
def add_to_cart(product_id):
    
    user = current_user
    product = Product.query.get(product_id)
    if product:
        user.addCart(product)
    return redirect(url_for('cart.show_cart'))


@cart.route('/remove_from_cart/<int:product_id>')
def remove_from_cart(product_id):
    cart_items = user.add_to_cart.all()
    user = current_user
    product = Product.query.get(product_id)
    if product in cart_items:
        user.removeCart(product)


    return redirect(url_for('cart.show_cart'))

app/routes.py
from app import app

from flask import render_template
import requests

from app.models import Product

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/products')
def get_products():
    response = requests.get(f"https://fakestoreapi.com/products/")
    if response.ok:
        products = response.json()
        prod_info_list = []
        for p in products:
            product_info = {
                'ID': p['id'],
                'Name': p['title'],
                'Price': p['price'],
                'Description': p['description'],
                'Image': p['image']
            }
            prod_info_list.append(product_info)
        return render_template('products.html', data=prod_info_list)

@app.route('/products/<int:product_id>')
def get_product(product_id):
    response = requests.get(f"https://fakestoreapi.com/products/{product_id}")
    if response.ok:
        product = response.json()
        product_info = {
            'Name': product['title'],
            'Price': product['price'],
            'Description': product['description'],
            'Image': product['image']
        }
# need to a function to add product to database
        print(product_info)
        return render_template('product.html', data=product_info)

app/templates/index.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
</head>

<body>
    <h1></h1>

    {% include 'nav.html' %}

    {% block content %}

    {% endblock %}
   
   
   
   
   
   
   
   
   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/nav.html
<nav class="navbar navbar-expand-xxl custom-navbar">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">THE AWESOME STORE</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/login">Log In</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/register">Sign Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/products">Products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/app/cart/cart_templates/cart.html">My Cart</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button type="button" class="btn btn-success" onclick="alert('Sorry, we are out of that product.')">Search</button>
        </form>
      </div>
    </div>
  </nav>

app/templates/product.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Products</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
</head>

<body>
    {% include 'nav.html' %}
    <div class="container d-flex justify-content-center mt-5">
        <div class="card" style="width: 18rem;">
            <img src="{{ data['Image'] }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h1 class="card-title">{{ data['Name'] }}</h1>
                <h6 class="card-text">{{ data['Description'] }}</h6>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">${{ data['Price'] }}</li>
            </ul>
            <div class="card-body">
                <a href="#" class="btn btn-primary">Add to cart</a>
                <!-- need route link -->
                <a href="/products" class="btn btn-warning">Go Back</a>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/products.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Products</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
</head>

<body>
    {% include 'nav.html' %}

    <div class="card-grid">
        {% for d in data %}
        <div class="card" style="width: 18rem;">
            <img src="{{ d['Image'] }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h1 class="card-title">{{ d['Name'] }}</h1>
                <h6 class="card-text">{{ d['Description'] }}</h6>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">${{ d['Price'] }}</li>

            </ul>
            
            <div class="card-body">
                <a href="{{ url_for('get_product', product_id=d['ID']) }}" class="btn btn-danger">View</a>
                <a href="{{ url_for('cart.add_to_cart', product_id=d['ID']) }}" class="btn btn-primary">Add to cart</a>
                <!-- need to add route link to button -->
            </div>
        </div>
        {% endfor %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</body>

</html>